"""Guardrails (spec §15): what the agent refuses, and how outside text is kept from steering it.

Go validates requests first (Section 3); these checks are defence in depth inside the worker.
"""

from __future__ import annotations

import json
import re
from datetime import date
from functools import lru_cache
from pathlib import Path

from pydantic import BaseModel
from pyproj import Geod
from shapely.geometry import shape
from shapely.geometry.base import BaseGeometry
from shapely.prepared import prep

from inland_worker.contracts.models import DateRange
from inland_worker.kit.imagery import repair

MAX_AREA_KM2 = 5_000  # per-job cap, unchanged by the region (ADR-011/012)
MAX_RANGE_DAYS = 3 * 366
# the supported region (ADR-012): the 50 states + DC, generated by scripts/build_region_seed.py; the Go API
# validates against the same outline in PostGIS (reference_layers.region)
REGION_FILE = Path(__file__).resolve().parents[3] / "config" / "regions" / "usa.geojson"
REGION_NAME = "the United States"


@lru_cache
def region() -> BaseGeometry:
    return shape(json.loads(REGION_FILE.read_text())["features"][0]["geometry"])


@lru_cache
def _region_check():  # ~1 km tolerance for the simplified coastline; prepared: fast repeated contains()
    return prep(region().buffer(0.01))


OFFICIAL_HELP = (
    "This tool is for research, not emergencies. For evacuation orders and safety information, call 911 "
    "or follow your local fire agency and your county's emergency alerts."
)

EMERGENCY = re.compile(
    r"\b(evacuat\w*|escape route|should (i|we) (leave|stay|go)|is it safe|am i in danger|"
    r"shelter in place|emergency|911|where do i go)\b",
    re.I,
)
PREDICTION = re.compile(
    r"\b(predict\w*|forecast where|where will .{0,40}(start|ignite|spread)|next fire|"
    r"will .{0,30}(catch fire|burn next))\b",
    re.I,
)


class ScopeDecision(BaseModel):
    ok: bool
    code: str | None = None
    message: str | None = None


def area_km2(area) -> float:
    return abs(Geod(ellps="WGS84").geometry_area_perimeter(repair(area))[0]) / 1e6


def check_scope(question: str, area: dict, date_range: DateRange, today: date) -> ScopeDecision:
    q = question.strip()
    if not q or len(q) > 2000:
        return ScopeDecision(
            ok=False, code="INVALID_QUESTION", message="Ask a question of up to 2,000 characters."
        )
    if EMERGENCY.search(q):
        return ScopeDecision(ok=False, code="EMERGENCY_REDIRECT", message=OFFICIAL_HELP)
    if PREDICTION.search(q):
        return ScopeDecision(
            ok=False,
            code="UNSUPPORTED_PREDICTION",
            message="This tool analyses what happened; it can't predict where fires will start or "
            "spread. For current fire information, see your state's fire agency or inciweb.nwcg.gov.",
        )
    try:
        geom = repair(area)
    except (ValueError, TypeError, KeyError):
        return ScopeDecision(ok=False, code="INVALID_GEOMETRY", message="The area must be a valid polygon.")
    if not _region_check().contains(geom):
        return ScopeDecision(
            ok=False,
            code="AREA_OUTSIDE_REGION",
            message=f"The area must be inside {REGION_NAME} (the supported region).",
        )
    if area_km2(geom) > MAX_AREA_KM2:
        return ScopeDecision(
            ok=False, code="AREA_TOO_LARGE", message=f"Choose an area under {MAX_AREA_KM2:,} km²."
        )
    if date_range.end > today:
        return ScopeDecision(ok=False, code="DATE_IN_FUTURE", message="Dates must not be in the future.")
    if (date_range.end - date_range.start).days > MAX_RANGE_DAYS:
        return ScopeDecision(
            ok=False, code="DATE_RANGE_TOO_LONG", message="Choose a date range of up to 3 years."
        )
    return ScopeDecision(ok=True)


_CONTROL = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")


def untrusted(value: object, limit: int = 400) -> str:
    """Outside text (provider fields, alert descriptions) goes to the model only inside <data> tags, flattened and
    truncated, with no angle brackets, so it can't close the tag or pose as instructions."""
    text = _CONTROL.sub(" ", str(value)).replace("<", "(").replace(">", ")")
    text = re.sub(r"\s+", " ", text).strip()
    return f"<data>{text[:limit]}{'…' if len(text) > limit else ''}</data>"
